version: "3"
services:
  db:
    restart: always
    image: postgres:9.5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    restart: always
    image: quay.io/lesspass/backend:latest
    ports:
      - 8000:8000
    environment:
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
      - SECRET_KEY=azertyuiop
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
      - EMAIL_HOST=localhost
      - EMAIL_PORT=25
      - EMAIL_HOST_USER= 
      - EMAIL_HOST_PASSWORD= 
      - EMAIL_USE_TLS=0
    links:
      - db
